---
name: 'new-release'
title: '{{ env.GH_REL }}'
labels: ',needs-triage'
name: issue {{ env.GH_REL }}
description: File a bug report.
title: "{{ env.GH_REL }} "
labels: ["pull-request", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      value: "A bug happened!"

