---
name: issue 
description: File a bug report.
title: title 
labels: ["pull-request", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "what is the cause"
      value: "A bug happened!"
