---
name: issue {{ env.GH_REL }}
description: File a bug report.
title: "{{ env.GH_REL }} "
labels: ["pull-request", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "what is the cause"
      value: "A bug happened!"

