name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "what is the cause"
      value: "A bug happened!"
