# This is a basic workflow to help you get started with Actions

name: NewReleaseCheckout

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '*/3 * * * *'  # Runs every 30 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        id: get_release
        env:
          REPO: "owner/public-repo-name"  # Replace with the public repo owner and name
        run: |
          response=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/ALPHA-Charlott/azure-monitor-baseline-alerts/releases)
          echo "::set-output name=release::$response"

